### ISSUE TITLE
installation fail due to pysam old version

### ISSUE THREAD

**Issue by mbourgey** [abishara/athena_meta#1]
Hi,

the installation failled due to htslib / pysam version 0.9.0.
I
C -Ipysam -I. -Ihtslib -I/lb/project/mugqic/analyste_dev/software/python/Python-2.7.13/include/python2.7 -c htslib/hfile_libcurl.c -o build/temp.linux-x86_64-2.7/htslib/hfile_libcurl.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    htslib/hfile_libcurl.c: In function ‘easy_errno’:
    htslib/hfile_libcurl.c:93:10: error: ‘CURLE_NOT_BUILT_IN’ undeclared (first use in this function)
         case CURLE_NOT_BUILT_IN:
              ^
    htslib/hfile_libcurl.c:93:10: note: each undeclared identifier is reported only once for each function it appears in
   
I resolved it by modifying the version to 0.9.1 in the requirement.txt file.

**Comment by abishara** [comment]
Thanks!  This is updated now

**Comment by caot** [comment]
The following could be helpful to someone.

installed : /path-to/curl-7.50.3

export CFLAGS=-I/path-to/curl-7.50.3/include
