### ISSUE TITLE
seed_ctgs when continuing from aborted run

### ISSUE THREAD

**Issue by bsiranosian** [abishara/athena_meta#12]
I have a run that aborted midway through the pipeline, when resuming I got this error:
```
============================== bin_reads ==============================
--> 0 chunks need to be run. Skipping...

============================== index_reads ==============================
--> 0 chunks need to be run. Skipping...

============================== assemble_bins ==============================
--> 0 chunks need to be run. Skipping...

============================== assemble_olc ==============================
1 chunks to run. Starting...
2018-09-30 13:41:25 - --starting logging AssembleOLCStep --
2018-09-30 13:41:25 - jointly assemble bins with OLC
2018-09-30 13:41:25 - merge input contigs
orig ctgs 13476
filtered ctgs 9755
2018-09-30 13:41:40 - ========== Exception ==========
2018-09-30 13:41:40 - Traceback (most recent call last):
2018-09-30 13:41:40 -   File "/ifs/scratch/bsiranos/miniconda3/envs/py27/lib/python2.7/site-packages/athena/pipeline.py", line 50, in _
run_chunk
2018-09-30 13:41:40 -     chunk.run()
2018-09-30 13:41:40 -   File "/ifs/scratch/bsiranos/miniconda3/envs/py27/lib/python2.7/site-packages/athena/stages/assemble_olc.py", li
ne 102, in run
2018-09-30 13:41:40 -     for ctg in seed_ctgs:
2018-09-30 13:41:40 - UnboundLocalError: local variable 'seed_ctgs' referenced before assignment
```
Adding this snippet of code (taken from from the above block) to assemble_olc.py solved the issue:

    if not os.path.isfile(mergedfiltfa_path):
      filter_inputs(
        mergedbam_path,
        premergedfa_path,
        premergedfiltfa_path,
      )

      # append input seed contigs
      with open(seedsfa_path, 'w') as fout:
        fasta = pysam.FastaFile(self.options.ctgfasta_path)

>>        bins = util.load_pickle(self.options.bins_pickle_path)
>>        seed_ctgs = set()
>>        for (binid, seed_group) in bins:
>>          for ctg in seed_group:
>>            seed_ctgs.add(ctg)

        for ctg in seed_ctgs:  
          seq = str(fasta.fetch(ctg).upper())
          for i in xrange(5):
          #for i in xrange(2):
            fout.write('>{}.{}\n'.format(ctg, i))
            fout.write(str(seq) + '\n')

      util.concat_files(
        [premergedfiltfa_path, seedsfa_path], 
        mergedfiltfa_path,
      )
    assert is_valid_fasta(mergedfiltfa_path), "merge FASTA not valid"

**Comment by abishara** [comment]
Hi,

Is this running with a particular version?  If not, what is the commit hash for the particular version you are running?  Line 102 in assemble_olc.py in HEAD of both 'main' and 'dev' branches does not match what you copied or what is present in the error message.

**Comment by bsiranosian** [comment]
Yes, you're right what was in my anaconda environment was slightly different than the most recent commit in the dev branch. I reinstalled and hopefully won't have the error again, sorry about that.

**Comment by abishara** [comment]
No problem, thanks for letting me know.
