### ISSUE TITLE
Install with conda, not pip

### ISSUE THREAD

**Issue by vinisalazar** [abishara/athena_meta#13]
Hello, 

I highly recommend that you update your install instructions to create and install athena_meta with a  conda environment instead of a venv, based on the fact that you have numpy as a requirement. When numpy is installed with conda instead of pip, the mkl (Math Kernel Library) comes as a dependency, and numpy leverages the power of that library, drastically increasing its performance, as described [here.](https://docs.anaconda.com/mkl-optimizations/)

Furthermore, conda has become more or less the preferred platform for distribution of scientific packages, therefore I'd also recommend creating a conda recipe for the installation of athena_meta itself. If there is interest in your part, I can contribute by doing that.

Sincerely
V

**Comment by dksam** [comment]
I will be extremely thankful if you can kindly make a conda recipe for the installation of athena_meta

**Comment by abishara** [comment]
Hi,

Pull requests are welcomed and I would be open to including this.

Thanks!
alex

**Comment by vinisalazar** [comment]
Hello @dksam and @abishara, thank you for the reply.

Hopefully I will find time to do this within the next couple of weeks. If so, I will post an update here.

**Comment by abishara** [comment]
Okay that sounds good.

alex

**Comment by Zhong17** [comment]
Hope the  installation of athena_meta on conda coming soon!

**Comment by vinisalazar** [comment]
@Zhong17 Sorry I completely forgot about this. I'll post here when there is an update, and hopefully if someone has beat me to it they'll do the same

**Comment by abishara** [comment]
Okay, the latest release (1.3) of Athena is now available through conda as referenced in the README 
https://github.com/abishara/athena_meta/blob/main/README.md

https://anaconda.org/bioconda/athena_meta

Hope this is helpful.  Please let me know if there are any issues.

Best,
alex

**Comment by vinisalazar** [comment]
Thank you @abishara
