### ISSUE TITLE
input generation

### ISSUE THREAD

**Issue by mbourgey** [abishara/athena_meta#2]
Hi, 
this is not an issue per say but I didn't find any tools that are able to generate the fastq file in the format required for Athena. Do you have any insights for that purpose ? 

I was thinking aligning the fastq file with the standard tools (longranger/lariat) and extract the information from the bam file. 

Thank you in advance

Mat

**Comment by abishara** [comment]
Hey Mat,

I think that longranger basic/mkfastq should generate a barcoded fastq with the BX tag?  At least this was the case in the past when we ran it on our first sequenced samples, but that was nearly a year ago now.  I recently updated Athena a couple of days ago to allow the BX tag, which longranger generates, as well as the BC tag we originally requested.

Why would you need to align it to extract the barcode information?  These are metagenome reads you are using right?

Let me know if one of the basic pipelines from longranger can’t produce these inputs.

Thanks!
alex

On Jun 19, 2017, at 8:00 AM, mbourgey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
this is not an issue per say but I didn't find any tools that are able to generate the fastq file in the format required for Athena. Do you have any insights for that purpose ?

I was thinking aligning the fastq file with the standard tools (longranger/lariat) and extract the information from the bam file.

Thank you in advance

Mat

**Comment by mbourgey** [comment]
Hi Alex, 

yes the Iongranger basic should slove my issue. I din't see this option at the beginning in the 10x documentation. It is why I was planning previously to do a fake alignment and then extract the BC tag.  I launch the basic and it should work for me (it is still running) 

Thank you for you answer

Mat
