### ISSUE TITLE
Sample json

### ISSUE THREAD

**Issue by juansearch** [abishara/athena_meta#20]
Dear Athena,
I am not familiar with json format, do you have an example for the required input files?
Thanks,
Juan

**Comment by jebard** [comment]
I saw this in an older closed issue ;

The basic skeleton of a json is something like this: 

{
    "ctgfasta_path" : "path/to",
    "reads_ctg_bam_path" : "path/to",
    "input_fqs" : "path/to"
}

**Comment by abishara** [comment]
I updated the README to reference this basic skeleton in 48ab905eb2d9e0208cb47e692d5de092ab71fc3d

Hope this clarifies things.
