### ISSUE TITLE
Example config.json file missing

### ISSUE THREAD

**Issue by aleu785** [abishara/athena_meta#6]
Hello Alex

I was wondering if you can provide an example of a config.json file you used to run the assembler since it seems to be missing.

Thanks,
Andy

**Comment by abishara** [comment]
Hi Andy,

The three required fields are specified in the README and they consist of three paths.  I’ve attached a very simple skeleton config.json to run in multiprocessing mode using four cores.  Please let me know if it is still unclear.

Thanks!
alex


On Sep 25, 2017, at 12:22 AM, uqaleu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Alex

I was wondering if you can provide an example of a config.json file you used to run the assembler since it seems to be missing.

Thanks,
Andy

**Comment by aleu785** [comment]
Hello Alex

Did you attach a skeleton config.json file? I cant seem to find it. 

Cheers,
Andy

**Comment by abishara** [comment]
Hi Andy,

Apparently replying and attaching in email doesn't go through.  How about now?  It won't let me attach a *json so I moved it to a *txt file.
[config.json.txt](https://github.com/abishara/athena_meta/files/1334411/config.json.txt)


alex

**Comment by aleu785** [comment]
Thanks Alex!

**Comment by aleu785** [comment]
Hello again Alex

I seemed to have run into this error and im not exactly sure what the
problem is:

2017-09-27 10:03:22 - --starting logging IndexReadsStep_Andynew --
2017-09-27 10:03:22 - index fastq
/srv/projects2/aom/10X/Andynew/outs/interleaved.seqpurged.fastq
2017-09-27 10:03:22 - ========== Exception ==========
2017-09-27 10:03:22 - Traceback (most recent call last):
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/pipeline.py",
line 50, in _run_chunk
2017-09-27 10:03:22 -     chunk.run()
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/stages/index_reads.py",
line 62, in run
2017-09-27 10:03:22 -     with FastqIndex(self.nfq_path, self.logger) as idx:
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/mlib/fq_idx.py",
line 35, in __init__
2017-09-27 10:03:22 -     self.__build_index__()
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/mlib/fq_idx.py",
line 70, in __build_index__
2017-09-27 10:03:22 -     lambda(x): x[0],
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/mlib/util.py",
line 117, in fastq_iter
2017-09-27 10:03:22 -     qname, _, bcode = lines[0].strip().split('\t')[:3]
2017-09-27 10:03:22 - ValueError: need more than 1 value to unpack
2017-09-27 10:03:22 -
2017-09-27 10:03:22 - need more than 1 value to unpack

Do you know what this means?

I noticed your example reads look like this:
@NS500418:354:H27G3BGXY:3:12612:25572:11380 RG:Z:readgroup1
BC:Z:GCCAATTCAAGTTT-1
TTCCATGTGGAAGTAGTTGTATTTGACGTAGCCCGCCATACCGTTTTCTGACATGAAGCGGTAATTCTCCTCAGAACCGTAGCCGGATACGGCCACCACCGTATGGGCCAACCTGTCATATCTGCTTGAGAAGGATTG
+
EEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEE6EEAEEEEAEEEEEEEEEEEEEEAEEEEEEEEEEEEEAEEEEEE

But mine looks like this:
@NS500333:151:HNM55AFXX:2:11308:1131:10378 BX:Z:ACACGATCATTGAAAG-1
TCTATGATTCCATCAAGGTTAGTAACATTAACCTTTGGTGGAATCATAGAAAAAATGCAGGGCGAAGGGACTAATGGGAAATTGATTGAGCTCAAGGCAGAGGATGATATGATTAATGTGGATGTGCCAGAGAAGCTATCAAAAGAGCTTG
+
AAA6AE6EEEE/EEAEEEEEEEE<AAEEAEEEEEEEEEEEEEEEAAE6E/AA6EEEEEAEEEEE6AEEE/EE6AEAEE66AEEE/EAE/<EAE//AAA////6/E//E/EA/E///AEAE/<A//<</<</A//A/E/<<//////E<</6


Would this be the reason for the error? Also when you were generating
the reads, did you use the longranger makefastq and basic proram?

Cheers,
Andy

**Comment by aleu785** [comment]
Hello again Alex

I seemed to have run into this error and im not exactly sure what the
problem is:

2017-09-27 10:03:22 - --starting logging IndexReadsStep_Andynew --
2017-09-27 10:03:22 - index fastq
/srv/projects2/aom/10X/Andynew/outs/interleaved.seqpurged.fastq
2017-09-27 10:03:22 - ========== Exception ==========
2017-09-27 10:03:22 - Traceback (most recent call last):
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/pipeline.py",
line 50, in _run_chunk
2017-09-27 10:03:22 -     chunk.run()
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/stages/index_reads.py",
line 62, in run
2017-09-27 10:03:22 -     with FastqIndex(self.nfq_path, self.logger) as idx:
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/mlib/fq_idx.py",
line 35, in __init__
2017-09-27 10:03:22 -     self.__build_index__()
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/mlib/fq_idx.py",
line 70, in __build_index__
2017-09-27 10:03:22 -     lambda(x): x[0],
2017-09-27 10:03:22 -   File
"/srv/sw/miniconda3/envs/athena_1.0/lib/python2.7/site-packages/athena/mlib/util.py",
line 117, in fastq_iter
2017-09-27 10:03:22 -     qname, _, bcode = lines[0].strip().split('\t')[:3]
2017-09-27 10:03:22 - ValueError: need more than 1 value to unpack
2017-09-27 10:03:22 -
2017-09-27 10:03:22 - need more than 1 value to unpack

Do you know what this means?

I noticed your example reads look like this:
@NS500418:354:H27G3BGXY:3:12612:25572:11380 RG:Z:readgroup1
BC:Z:GCCAATTCAAGTTT-1
TTCCATGTGGAAGTAGTTGTATTTGACGTAGCCCGCCATACCGTTTTCTGACATGAAGCGGTAATTCTCCTCAGAACCGTAGCCGGATACGGCCACCACCGTATGGGCCAACCTGTCATATCTGCTTGAGAAGGATTG
+
EEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEE6EEAEEEEAEEEEEEEEEEEEEEAEEEEEEEEEEEEEAEEEEEE

But mine looks like this:
@NS500333:151:HNM55AFXX:2:11308:1131:10378 BX:Z:ACACGATCATTGAAAG-1
TCTATGATTCCATCAAGGTTAGTAACATTAACCTTTGGTGGAATCATAGAAAAAATGCAGGGCGAAGGGACTAATGGGAAATTGATTGAGCTCAAGGCAGAGGATGATATGATTAATGTGGATGTGCCAGAGAAGCTATCAAAAGAGCTTG
+
AAA6AE6EEEE/EEAEEEEEEEE<AAEEAEEEEEEEEEEEEEEEAAE6E/AA6EEEEEAEEEEE6AEEE/EE6AEAEE66AEEE/EAE/<EAE//AAA////6/E//E/EA/E///AEAE/<A//<</<</A//A/E/<<//////E<</6


Would this be the reason for the error? Also when you were generating
the reads, did you use the longranger makefastq and basic proram?

Cheers,
Andy

**Comment by abishara** [comment]
Hi Andy,

Your *fastq looks fine from that single entry excerpt, and yes we use longranger makefastq+basic to generate our input *fastq files.  The error you encountered has since been addressed in the source repo.  Can you update to the latest version and give it another try?  Let me know if that takes care of it.

Thanks!
alex

**Comment by Zhong17** [comment]
Hello  Alex
when i used long ranger basic to deal with my 10X data, I found that the extracted barcoded reads were  fewer than other software, which may due to the strict criterion. Is there any parameter for long ranger basic to relax such criterion: for example, the extracted barcode my be allowed to have N.
Thanks
alex

**Comment by abishara** [comment]
Hi,

I recommend contacting the software support at 10X to ask why their longranger basic software is giving less reads than you expect from one of their libraries. 

Please feel free to create another issue if you encounter issues with using the resulting barcoded *fastq with Athena.

Best,
alex
