### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by vphan13** [abishara/athena_meta#9]
OS = CentOS release 6.2 (Final)
`[root@server1 athena_meta-main]# echo $PATH
/usr/local/packages/bwa-0.7.15/bin:/usr/local/packages/idba-1.1.3a1/bin:/usr/local/packages/samtools-1.3.1/bin:/usr/local/packages/htslib-1.3.2/bin:/usr/local/packages/flye-2.3.4/bin:/usr/local/packages/python-2.7.15/bin:$PATH`

All python prerequisites have been installed 

`[root@server1 athena_meta-main]# pip --no-cache-dir install -r requirements.txt
Requirement already satisfied: bx-python==0.7.3 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (0.7.3)
Requirement already satisfied: ipython-cluster-helper==0.5.2 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.5.2)
Requirement already satisfied: numpy==1.11.0 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.11.0)
Requirement already satisfied: pysam==0.9.1 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.9.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (39.0.1)
Requirement already satisfied: pyzmq>=2.1.11 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (17.0.0)
Requirement already satisfied: ipython<5.0.0,>=4.0.0 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (4.2.1)
Requirement already satisfied: ipyparallel>=4.0.0 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (6.1.1)
Requirement already satisfied: netifaces>=0.10.3 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (0.10.7)
Requirement already satisfied: decorator in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (4.3.0)
Requirement already satisfied: pickleshare in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (0.7.4)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (0.8.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (4.5.0)
Requirement already satisfied: traitlets in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (4.3.2)
Requirement already satisfied: tornado>=4 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (5.0.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (2.7.3)
Requirement already satisfied: jupyter-client in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (5.2.3)
Requirement already satisfied: ipykernel in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (4.8.2)
Requirement already satisfied: ipython-genutils in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: futures; python_version == "2.7" in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: pathlib2; python_version in "2.6 2.7 3.2 3.3" in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from pickleshare->ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (2.3.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (0.5.2)
Requirement already satisfied: six in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from traitlets->ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from traitlets->ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (1.1.6)
Requirement already satisfied: singledispatch in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from tornado>=4->ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (3.4.0.3)
Requirement already satisfied: backports_abc>=0.4 in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from tornado>=4->ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (0.5)
Requirement already satisfied: jupyter-core in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from jupyter-client->ipyparallel>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (4.4.0)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/packages/python-2.7.15/lib/python2.7/site-packages (from pathlib2; python_version in "2.6 2.7 3.2 3.3"->pickleshare->ipython<5.0.0,>=4.0.0->ipython-cluster-helper==0.5.2->-r requirements.txt (line 2)) (1.7)`

When attempting athena_meta install via pip

` pip -r install -vvv .`

`Traceback (most recent call last):
  File "/usr/local/packages/python-2.7.15/lib/python2.7/site-packages/pip/_internal/utils/outdated.py", line 140, in pip_version_check
    state.save(pypi_version, current_time)
  File "/usr/local/packages/python-2.7.15/lib/python2.7/site-packages/pip/_internal/utils/outdated.py", line 73, in save
    state = json.load(statefile)
  File "/usr/local/packages/python-2.7.15/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/packages/python-2.7.15/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/packages/python-2.7.15/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/packages/python-2.7.15/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by vphan13** [comment]
This issue was cause by a corrupt python cache on the system used to install.  I was unable to replicate the above on another system.  Using `pip install --no-cache-dir -v .` I was able to get everything working.

**Comment by abishara** [comment]
Great, thanks for the update!
